### ISSUE TITLE
update the yum package index

### ISSUE THREAD

**Issue by michaelsstuff** [lutangar/ansible-role-steamcmd#3]
Hi,

yum * latest **does not** update the package index, but updates every installed package on the system.
```
- name: update the yum package index
  yum:
    name: "*"
    state: latest
  when: ansible_pkg_mgr == "yum"
```

This needs to be removed, as a system update should absolutely not be included in a steamcmd install. If you really are concerned about yum cache check the option "update_cache".

-> https://docs.ansible.com/ansible/latest/modules/yum_module.html

cheers
Michael
